version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile_frontend
    ports:
      - "8501:8501"
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile_backend
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
